- arguments:
  # NOTE: List of extensions below should reflect the list
  #   of default extensions from package.yaml.
  - -XOverloadedStrings
  - -XTemplateHaskell
  - -XQuasiQuotes
  - -XScopedTypeVariables
- ignore: {name: Use camelCase}
- ignore: {name: Eta reduce}
- ignore: {name: Use first} 
- ignore: {name: Use second} 
- ignore: {name: Use unless} 
- ignore: {name: Use $>} 
- ignore: {name: Evaluate}
- ignore: {name: Use maybe} 
- ignore: {name: Use zipWith} 
- ignore: {name: Use TH quotation brackets} 
- ignore: {name: Use list comprehension} 
- ignore: {name: Use /=} 