- arguments:
  # NOTE: List of extensions below should reflect the list
  #   of default extensions from package.yaml.
  - -XOverloadedStrings
  - -XTemplateHaskell
  - -XQuasiQuotes
  - -XScopedTypeVariables
- ignore: {name: Use camelCase}
- ignore: {name: Eta reduce}
- ignore: {name: Redundant bracket}
- ignore: {name: Redundant $}
- ignore: {name: Redundant return} 
- ignore: {name: Move brackets to avoid $}
- ignore: {name: Use first} 
- ignore: {name: Use second} 
- ignore: {name: Use unless} 
- ignore: {name: Use newtype instead of data} 
- ignore: {name: Use $>} 
- ignore: {name: Evaluate}
- ignore: {name: Use maybe} 
- ignore: {name: Use ++} 
- ignore: {name: Unused LANGUAGE pragma} 
- ignore: {name: Use zipWith} 
- ignore: {name: Use TH quotation brackets} 
- ignore: {name: Use list comprehension} 
- ignore: {name: Use /=} 
- ignore: {name: Use concatMap} 