name: "*nix"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master 

defaults:
  run:
    shell: bash -l {0}

jobs:
  cancel:
    name: "Cleanup"
    runs-on: ubuntu-latest
    steps:
      - name: "Get workflow id"
        run: |
          WORKFLOW_ID=$(curl "Authorization: token ${{ github.token }}" https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ workflow_id }} | jq '.id')
          echo "Workflow id: ${WORKFLOW_ID}"
          echo "WORKFLOW_ID=${WORKFLOW_ID}" >> $GITHUB_ENV

      - uses: styfle/cancel-workflow-action@0.3.1
        with:
          access_token: ${{ github.token }}
          workflow_id: ${{ env.WORKFLOW_ID }}

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - uses: actions/checkout@main
        with:
          submodules: recursive

      - uses: actions/setup-haskell@v1.1
        with:
          ghc-version: 'latest'
          enable-stack: true
          stack-version: 'latest'

      - name: Set up environment
        run: |
          mkdir -p ~/.local/bin
          echo "$HOME/.local/bin:$PATH" >> $GITHUB_PATH

      - name: Verify Haskell/stack
        run: |
          stack --numeric-version
          ghc --version
          
      - name: Build dependencies 
        run: |
          cd waspc
          stack --no-terminal --install-ghc test --only-dependencies
      
      - name: Build Wasp
        run: |
          cd waspc
          stack --no-terminal test
