name: "*nix"

# Triggered for commits/PRs on master branch
# + new tags

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master 
  create:
    tags:
      - v*

defaults:
  run:
    shell: bash -l {0}

jobs:
  # Cancel previous actions
  cancel:
    name: "Cleanup"
    runs-on: ubuntu-latest
    steps:
      - name: "Get workflow id"
        run: |
          WORKFLOW_ID=$(curl "Authorization: token ${{ github.token }}" https://api.github.com/repos/${{ github.repository }}/actions/workflows/nix.yaml | jq '.id')
          echo "Workflow id: ${WORKFLOW_ID}"
          echo "WORKFLOW_ID=${WORKFLOW_ID}" >> $GITHUB_ENV

      - uses: styfle/cancel-workflow-action@0.3.1
        with:
          access_token: ${{ github.token }}
          workflow_id: ${{ env.WORKFLOW_ID }}

  # Main build
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: recursive

      # Setup Haskell
      - name: Setup environment
        uses: actions/setup-haskell@v1.1
        with:
          ghc-version: 'latest'
          enable-stack: true
          stack-version: 'latest'

      # Verify everything's right
      - name: Verify haskell/stack
        run: |
          stack --numeric-version
          ghc --version
          
      # Build dependencies
      - name: Build dependencies 
        run: |
          cd waspc
          stack --no-terminal test --only-dependencies
      
      # Build Wasp
      - name: Build Wasp
        run: |
          cd waspc
          stack --no-terminal test
